version: '3'
services:
  rabbitmq:
      image: rabbitmq:management
      environment:
        - "RABBITMQ_DEFAULT_USER=root"
        - "RABBITMQ_DEFAULT_PASS=root"
        - "RABBITMQ_DEFAULT_VHOST=rabbitmq"
      ports:
        - "5672:5672"
        - "15672:15672"
  mysql:
      image: mysql:5.6
      environment:
          MYSQL_DATABASE: demo
          MYSQL_ROOT_PASSWORD: root
      ports:
          - "3306:3306"
