services:
    _defaults:
            autowire: true
            autoconfigure: true
            public: false

    Darkilliant\ImportBundle\Registry\:
        resource: '../../Registry/*'

    Darkilliant\ImportBundle\Step\:
        resource: '../../Step/*'
        autoconfigure: false
        public: true

    Darkilliant\ImportBundle\Loader\:
        resource: '../../Loader/*'
        public: true

    Darkilliant\ImportBundle\Resolver\EntityResolver:
        arguments:
            $config: '%darkilliant_import_field_entity_resolver%'
            $cacheable: '%darkilliant_import_entity_resolver_cache%'

    Cocur\Slugify\Slugify:
        public: true