services:
    _defaults:
            autowire: true
            autoconfigure: true
            public: false

    Darkilliant\ProcessBundle\Registry\:
        resource: '../../Registry/*'

    Darkilliant\ProcessBundle\Runner\:
        resource: '../../Runner/*'

    Darkilliant\ProcessBundle\StatDumper\:
        resource: '../../StatDumper/*'
        public: true

    Darkilliant\ProcessBundle\ProcessNotifier\ChainProcessNotifier:
        public: true

    Darkilliant\ProcessBundle\ProcessNotifier\ProgressBarProcessNotifier:
        tags: [{ name: darkilliant_process_notifier }]

    Darkilliant\ProcessBundle\ProcessNotifier\BreakerProcessNotifier:
        tags: [{ name: darkilliant_process_notifier }]

    Darkilliant\ProcessBundle\ProcessNotifier\StatsCollectorProcessNotifier:
        public: true
        tags: [{ name: darkilliant_process_notifier }]

    Darkilliant\ProcessBundle\Runner\StepRunner:
        public: true
        arguments:
            $logger: '@logger'
            $configuration: '%darkilliant_process%'

    Darkilliant\ProcessBundle\Runner\StepDescripterRunner:
        public: true
        arguments:
            $logger: '@logger'
            $configuration: '%darkilliant_process%'

    Darkilliant\ProcessBundle\Step\:
        resource: '../../Step/*'
        public: true

    Darkilliant\ProcessBundle\Step\LaunchIsolateProcessStep:
        arguments:
            $environment: '%kernel.environment%'

    Darkilliant\ProcessBundle\Logger\InMemoryLogger:
        public: true

    process_logger_default:
        public: true
        alias: 'logger'
